- type: html
  source: |
    <div style="padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); text-align: center;">
      <h1 style="color: #333; font-size: 18px; margin-bottom: 10px;">Welcome to My Page</h1>
      <p style="color: #666; font-size: 14px; margin-bottom: 20px;">Here you can find links to my projects and blogs.</p>
      <a href="https://github.com/sjsage522" target="_blank" style="display: inline-block; margin: 10px; text-decoration: none; color: #007BFF; font-weight: bold; font-size: 16px;">GitHub</a>
      <a href="https://jundol97.medium.com/" target="_blank" style="display: inline-block; margin: 10px; text-decoration: none; color: #007BFF; font-weight: bold; font-size: 16px;">Blog</a>
    </div>
