- type: html
  source: |
    <div style="padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); text-align: center;">
      <h1 style="font-size: 18px; margin-bottom: 10px;">Welcome to My Page</h1>
      <p style="font-size: 14px; margin-bottom: 20px;">Here you can find links to my projects and blogs.</p>
      <a style="margin-right: 40px" href="https://github.com/sjsage522" target="_blank">GitHub</a>
      <a href="https://jundol97.medium.com/" target="_blank">Blog</a>
    </div>
