server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          !include: widgets/custom/intro.yml
          !include: widgets/clock.yml
          !include: widgets/calendar.yml
          !include: widgets/bookmarks.yml
      - size: full
        widgets:
          !include: widgets/rss/rss-blog.yml
      - size: small
        widgets:
          !include: widgets/custom/random-fact.yml
          !include: widgets/weather.yml
          !include: widgets/markets.yml
          !include: widgets/server-stats.yml

  - name: RSS
    columns:
      - size: full
        widgets:
          !include: widgets/rss/rss-youtube.yml
      - size: small
        widgets:
          !include: widgets/rss/rss-news.yml
      - size: full
        widgets:
          !include: widgets/rss/rss-tech.yml


  - name: Entertainment
    columns:
      - size: full
        widgets:
          !include: widgets/reddit.yml
      - size: small
        widgets:
          - type: group
            widgets:
              !include: widgets/custom/steam.yml

  - name: Releases
    columns:
      - size: full        
        widgets:
          - type: split-column
            widgets:
              !include: widgets/custom/glance-release.yml
              !include: widgets/releases.yml