server:
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css
  light: false
  background-color: 220 30 15
  primary-color: 220 25 25
  accent-color: 190 100 50
  text-color: 0 0 95

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          !include: widgets/custom/intro.yml
          !include: widgets/calendar.yml
          !include: widgets/bookmarks.yml
      - size: full
        widgets:
          !include: widgets/rss-blog.yml
      - size: small
        widgets:
          !include: widgets/weather.yml
          !include: widgets/markets.yml

  - name: RSS
    columns:
      - size: full
        widgets:
          !include: widgets/rss.yml

  - name: Entertainment
    columns:
      - size: full
        widgets:
          !include: widgets/reddit.yml
      - size: small
        widgets:
          - type: group
            widgets:
              !include: widgets/custom/steam.yml

  - name: Releases
    columns:
      - size: full
        widgets:
          !include: widgets/releases.yml
